# config/team_config.yaml

# Global view patterns - these are consistent across all teams

view_patterns:
  # Existing patterns
  community_all_time: "{prefix}_COMMUNITY_INDEXING_ALL_TIME"
  community_snapshot: "{prefix}_COMMUNITY_INDEXING_SNAPSHOT"
  community_yoy: "{prefix}_COMMUNITY_INDEXING_YOY"
  community_last_full_year: "{prefix}_COMMUNITY_INDEXING_LAST_FULL_YEAR"  # NEW

  category_all_time: "{prefix}_CATEGORY_INDEXING_ALL_TIME"
  category_snapshot: "{prefix}_CATEGORY_INDEXING_SNAPSHOT"
  category_yoy: "{prefix}_CATEGORY_INDEXING_YOY"
  category_last_full_year: "{prefix}_CATEGORY_INDEXING_LAST_FULL_YEAR"  # NEW

  subcategory_all_time: "{prefix}_SUBCATEGORY_INDEXING_ALL_TIME"
  subcategory_snapshot: "{prefix}_SUBCATEGORY_INDEXING_SNAPSHOT"
  subcategory_yoy: "{prefix}_SUBCATEGORY_INDEXING_YOY"
  subcategory_last_full_year: "{prefix}_SUBCATEGORY_INDEXING_LAST_FULL_YEAR"  # NEW

  merchant_all_time: "{prefix}_MERCHANT_INDEXING_ALL_TIME"
  merchant_snapshot: "{prefix}_MERCHANT_INDEXING_SNAPSHOT"
  merchant_yoy: "{prefix}_MERCHANT_INDEXING_YOY"
  merchant_last_full_year: "{prefix}_MERCHANT_INDEXING_LAST_FULL_YEAR"  # NEW

  community_merchant_all_time: "{prefix}_COMMUNITY_MERCHANT_INDEXING_ALL_TIME"
  community_merchant_snapshot: "{prefix}_COMMUNITY_MERCHANT_INDEXING_SNAPSHOT"
  community_merchant_yoy: "{prefix}_COMMUNITY_MERCHANT_INDEXING_YOY"
  community_merchant_last_full_year: "{prefix}_COMMUNITY_MERCHANT_INDEXING_LAST_FULL_YEAR"  # NEW

  demographics: "{prefix}_DEMOGRAPHICS_DIST"

# Team-specific configurations
teams:
  utah_jazz:
    team_name: "Utah Jazz"
    team_name_short: "Jazz"
    league: "NBA"
    view_prefix: "V_UTAH_JAZZ_SIL"  # Has SIL in the prefix
    colors:
      primary: "#002B5C"      # Jazz Navy (official dark blue)
      secondary: "#F9A01B"    # Jazz Gold (official yellow/gold)
      accent: "#00471B"
    audience_name: "Utah Jazz Fans"
    comparison_population: "Local Gen Pop (Excl. Jazz)"
    category_mode: "standard"  # Back to standard mode for testing

  carolina_panthers:
    team_name: "Carolina Panthers"
    team_name_short: "Panthers"
    league: "NFL"
    view_prefix: "V_CAROLINA_PANTHERS_SIL"  # Following NFL pattern (no SIL)
    colors:
      primary: "#0085CA"      # Panthers Blue (official)
      secondary: "#101820"    # Black (official)
      accent: "#BFC0BF"       # Silver (official)
    audience_name: "Carolina Panthers Fans"
    comparison_population: "Local Gen Pop (Excl. Carolina Panthers Fans)"
    category_mode: "standard"  # Use existing 6+4 category system

  oakland_roots:
    team_name: "Oakland Roots"
    team_name_short: "Roots"
    league: "USL"
    view_prefix: "V_OAKLAND_ROOTS_SIL"
    colors:
      primary: "#00A651"      # Oakland Roots Green (official)
      secondary: "#000000"    # Black (official)
      accent: "#FFFFFF"       # White (accent)
    audience_name: "Oakland Soccer Fans"  # Key customization - broader segment
    comparison_population: "Local Gen Pop (Excl. Oakland Soccer Fans)"
    market_size: "small"      # Flag for potential threshold adjustments
    
    # Category customization
    category_mode: "custom"    # Toggle: "standard" or "custom"
    custom_categories:
      count: 6                 # How many categories they want
      selected_categories:
        - "Restaurants"            # More relevant than national chains
        - "Attractions"            # Oakland-specific attractions
        - "Entertainment & News"   # Local entertainment
        - "Health"                 # Community health
        - "Education Resources"    # Local education
        - "Sportstainment"         # Sports-related entertainment
      thresholds:
        min_audience_pct: 0.15     # Lower than major league 0.20
        min_merchant_audience_pct: 0.05  # Lower than major league 0.10